### ISSUE TITLE
HDLC error

### ISSUE THREAD

**Issue by keomabrun** [realms-team/sol#28]
@Hdlc: Connection Error: Queue overflowed

@Hdlc: Connection Error: Unexpected manager_hello
Connecting to /dev/ttyUSB3... @Hdlc: Connection Error: Unexpected manager_hello
@Hdlc: received hdlc frame too short
PASS.

**Comment by zhangziran-ucb** [comment]
how did you fixed the "@Hdlc: Connection Error: Queue overflowed" error ?

**Comment by keomabrun** [comment]
We usually have that error when two process are trying to connect to the manager's API port at the same time. Can you confirm this is not you case ?
