### ISSUE TITLE
Some RSSI values are positive

### ISSUE THREAD

**Issue by keomabrun** [realms-team/sol#43]
https://sol.paris.inria.fr/grafana/dashboard/db/savethepeaches_details?panelId=29&fullscreen&from=1467496800000&to=1467707104124

By looking at the solmanager.backup HDLC file we can see that those values are not the same as in the database.

Similar issue arise for HR_DEVICE batteryVoltage for instance.

**Comment by twatteyne** [comment]
@keomabrun, can you remind me what the "solmanager.backup HDLC file" is? Did you track down the inconsistency?

**Comment by keomabrun** [comment]
@twatteyne, the solmanager is the file located at the solmanager that stores the objects locally before sending them to the solserver.
I still did not figure why this is happening but by trying to reproduce the issue, I found another issue when writing to the backup file: https://github.com/realms-team/sol/issues/44

**Comment by twatteyne** [comment]
OK, I remember now :-) happy chasing bugs! Probably a sign problem

**Comment by keomabrun** [comment]
Thanks !

**Comment by keomabrun** [comment]
On server side, after http_to_bin and bin_to_json, rssi has the right value.
The error can come from json_to_influx or when using the influxdb python library.
The chase continues.

**Comment by keomabrun** [comment]
By looking at the logs, I can finally say that this issue comes from influxdb...
Looking for a solution now...
