### ISSUE TITLE
Objects not ordered by timestamps in the backup file

### ISSUE THREAD

**Issue by keomabrun** [realms-team/sol#44]
When saving sol object to HDLC formated backup file, object are placed at the bottom of the file.
This makes objects timestamps not to be always increasing.
Objects should be inserted into the file according to there timestamp.

Example (objects extracted for HDLC backup file):
`
{'timestamp': 1464170641, 'mac': [0, 23, 13, 0, 0, 96, 8, 213], 'type': 39, 'value': {'temperature': 160}}`
`{'timestamp': 1464170468, 'mac': [0, 23, 13, 0, 0, 48, 96, 239], 'type': 39, 'value': {'temperature': 18}}
`

**Comment by twatteyne** [comment]
wow, good catch

**Comment by keomabrun** [comment]
@twatteyne, I will undo this commit. The buffer we talked about already exists.
The problem comes from the fact that the messages sometime have more than 3 min shift.
This shift is too huge to come from the dust network. It might append because the raspberry resync with NTP ?
