### ISSUE TITLE
temp_phys is saved as an integer instead of a float 

### ISSUE THREAD

**Issue by anadiedrichs** [realms-team/sol#62]
Temp_phys and similar fields are saved as an integer instead of a float. 

For e.g, if we have temp_raw=24334, temp_phys should be 19.97, after applying the conversion function in SolDefines.py, instead, temp_phys value is stored as 19, losing the precision.

**Comment by keomabrun** [comment]
Duplicate: https://github.com/realms-team/sol/issues/61
